# Generated by Django 2.0.6 on 2018-06-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-creat_at']},
        ),
    ]
